# Autogenerated wrapper script for PARI_jll for aarch64-unknown-freebsd
export gp, libpari, pari_desc

using GMP_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PARI")
JLLWrappers.@declare_library_product(libpari, "libpari-gmp-tls.so.9")
JLLWrappers.@declare_executable_product(gp)
JLLWrappers.@declare_file_product(pari_desc)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libpari,
        "lib/libpari.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        gp,
        "bin/gp",
    )

    JLLWrappers.@init_file_product(
        pari_desc,
        "share/pari/pari.desc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
